/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    'blog-posts': BlogPost;
    'blog-categories': BlogCategory;
    'bird-species': BirdSpecy;
    'bird-categories': BirdCategory;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    'bird-species': BirdSpeciesSelect<false> | BirdSpeciesSelect<true>;
    'bird-categories': BirdCategoriesSelect<false> | BirdCategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Edite as secoes de cada rota do site mantendo a mesma estrutura JSON.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Nome para identificar a pagina no CMS (nao aparece no site).
   */
  title?: string | null;
  /**
   * Use a rota completa, ex.: /, /blog, /observacao-de-aves.
   */
  slug: string;
  /**
   * Deixe vazio para usar automaticamente: "{title} | Itaicy Pantanal Eco Lodge". Maximo recomendado: 60 caracteres.
   */
  metaTitle?: string | null;
  /**
   * Deixe vazio para usar automaticamente os primeiros 155 caracteres do campo "title". Ideal: 120-155 caracteres.
   */
  metaDescription?: string | null;
  /**
   * Deixe vazio para usar automaticamente o campo "title". Tamanho ideal: 1200x630px.
   */
  ogImage?: string | null;
  /**
   * Marque para impedir que esta pagina apareca nos resultados de busca.
   */
  noIndex?: boolean | null;
  /**
   * Deixe vazio para usar automaticamente: "http://127.0.0.1:5000/{slug}". Preencha apenas se a URL canonica for diferente.
   */
  canonicalUrl?: string | null;
  /**
   * Cole aqui o JSON das secoes da pagina. Mantemos esta estrutura para paridade total com o frontend.
   */
  sections?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Central de imagens e arquivos visuais usados no site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descreva a imagem para leitores de tela e para melhorar SEO.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Gerencie os artigos do blog com categorias, destaque e conteudo estruturado.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  /**
   * Titulo principal do artigo. Aparece no card e na pagina.
   */
  title: string;
  /**
   * URL amigavel do artigo (somente minusculas e hifens).
   */
  slug: string;
  subtitle?: string | null;
  description?: string | null;
  tag?: string | null;
  primaryCategory?: (number | null) | BlogCategory;
  categories?: (number | BlogCategory)[] | null;
  src?: string | null;
  /**
   * Caminho da imagem principal usada no hero do artigo.
   */
  heroImage?: string | null;
  author?: string | null;
  date?: string | null;
  readingTime?: string | null;
  contentBlocks?:
    | (
        | {
            /**
             * Use **texto** para negrito (compativel com markdown).
             */
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading';
          }
        | {
            name: string;
            scientificName: string;
            description: string;
            /**
             * Caminho da imagem, ex: /images/bird-species-1
             */
            image?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'species';
          }
        | {
            items?:
              | {
                  bold: string;
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'orderedList';
          }
      )[]
    | null;
  /**
   * Deixe vazio para usar automaticamente: "{title} | Itaicy Pantanal Eco Lodge". Maximo recomendado: 60 caracteres.
   */
  metaTitle?: string | null;
  /**
   * Deixe vazio para usar automaticamente os primeiros 155 caracteres do campo "description". Ideal: 120-155 caracteres.
   */
  metaDescription?: string | null;
  /**
   * Deixe vazio para usar automaticamente o campo "heroImage". Tamanho ideal: 1200x630px.
   */
  ogImage?: string | null;
  /**
   * Marque para impedir que esta pagina apareca nos resultados de busca.
   */
  noIndex?: boolean | null;
  /**
   * Deixe vazio para usar automaticamente: "http://127.0.0.1:5000/blog/{slug}". Preencha apenas se a URL canonica for diferente.
   */
  canonicalUrl?: string | null;
  relatedPosts?: (number | BlogPost)[] | null;
  /**
   * Marque para exibir como artigo principal na pagina do blog.
   */
  isFeatured?: boolean | null;
  /**
   * Marque para exibir na secao 'Mais Recentes' do blog.
   */
  isRecent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Classifique os artigos para melhorar navegacao, filtros e SEO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  /**
   * Ex.: Aventura, Sustentabilidade, Gastronomia.
   */
  name: string;
  /**
   * URL amigavel da categoria. Use letras minusculas e hifens.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Catalogo de especies para paginas de observacao de aves e conteudo editorial.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bird-species".
 */
export interface BirdSpecy {
  id: number;
  commonName: string;
  scientificName: string;
  slug: string;
  description?: string | null;
  /**
   * Ex: Psittaciformes, Passeriformes
   */
  taxonomicOrder?: string | null;
  /**
   * Ex: Psittacidae, Thraupidae
   */
  family?: string | null;
  commonNameEN?: string | null;
  category?: (number | null) | BirdCategory;
  tag?: string | null;
  src?: string | null;
  heroImage?: string | null;
  author?: string | null;
  date?: string | null;
  /**
   * Status IUCN. Ex: 'Vulneravel (VU)', 'Pouco Preocupante (LC)'
   */
  conservationStatus?: string | null;
  size?: string | null;
  /**
   * Marque para exibir na secao de aves em destaque.
   */
  isFeatured?: boolean | null;
  habitat?: string | null;
  overview?: string | null;
  diet?: string | null;
  behavior?: string | null;
  bestTime?: string | null;
  /**
   * Dicas praticas para fotografar esta especie no Pantanal.
   */
  photographyTips?:
    | {
        tip: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Deixe vazio para usar automaticamente: "{commonName} | Itaicy Pantanal Eco Lodge". Maximo recomendado: 60 caracteres.
   */
  metaTitle?: string | null;
  /**
   * Deixe vazio para usar automaticamente os primeiros 155 caracteres do campo "description". Ideal: 120-155 caracteres.
   */
  metaDescription?: string | null;
  /**
   * Deixe vazio para usar automaticamente o campo "heroImage". Tamanho ideal: 1200x630px.
   */
  ogImage?: string | null;
  /**
   * Marque para impedir que esta pagina apareca nos resultados de busca.
   */
  noIndex?: boolean | null;
  /**
   * Deixe vazio para usar automaticamente: "http://127.0.0.1:5000/observacao-de-aves/catalogo/{slug}". Preencha apenas se a URL canonica for diferente.
   */
  canonicalUrl?: string | null;
  relatedSpecies?: (number | BirdSpecy)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Organize as especies por grupos para facilitar busca e filtragem.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bird-categories".
 */
export interface BirdCategory {
  id: number;
  /**
   * Ex.: Rapinantes, Aves aquaticas, Psitacideos.
   */
  name: string;
  /**
   * URL amigavel da categoria. Use letras minusculas e hifens.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gerencie os acessos de quem pode editar o site no CMS.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Nome exibido no painel administrativo.
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'bird-species';
        value: number | BirdSpecy;
      } | null)
    | ({
        relationTo: 'bird-categories';
        value: number | BirdCategory;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  noIndex?: T;
  canonicalUrl?: T;
  sections?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  description?: T;
  tag?: T;
  primaryCategory?: T;
  categories?: T;
  src?: T;
  heroImage?: T;
  author?: T;
  date?: T;
  readingTime?: T;
  contentBlocks?:
    | T
    | {
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        heading?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        species?:
          | T
          | {
              name?: T;
              scientificName?: T;
              description?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        orderedList?:
          | T
          | {
              items?:
                | T
                | {
                    bold?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  noIndex?: T;
  canonicalUrl?: T;
  relatedPosts?: T;
  isFeatured?: T;
  isRecent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bird-species_select".
 */
export interface BirdSpeciesSelect<T extends boolean = true> {
  commonName?: T;
  scientificName?: T;
  slug?: T;
  description?: T;
  taxonomicOrder?: T;
  family?: T;
  commonNameEN?: T;
  category?: T;
  tag?: T;
  src?: T;
  heroImage?: T;
  author?: T;
  date?: T;
  conservationStatus?: T;
  size?: T;
  isFeatured?: T;
  habitat?: T;
  overview?: T;
  diet?: T;
  behavior?: T;
  bestTime?: T;
  photographyTips?:
    | T
    | {
        tip?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  noIndex?: T;
  canonicalUrl?: T;
  relatedSpecies?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bird-categories_select".
 */
export interface BirdCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configuracoes globais compartilhadas em todo o site: contato, rodape, FAQ, depoimentos e secoes da home.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  contactAddress?: string | null;
  ctaHeading?: string | null;
  ctaDescription?: string | null;
  /**
   * Caminho da imagem, ex: /images/cta-bg
   */
  ctaBackgroundImage?: string | null;
  faqLabel?: string | null;
  faqHeading?: string | null;
  faqDescription?: string | null;
  /**
   * Adicione perguntas frequentes. Arraste para reordenar.
   */
  faqItems?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  testimonialsLabel?: string | null;
  testimonialsHeading?: string | null;
  testimonialsDescription?: string | null;
  testimonialItems?:
    | {
        quote: string;
        author: string;
        location?: string | null;
        rating?: number | null;
        id?: string | null;
      }[]
    | null;
  footerPousadaLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerExperienciasLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerLegalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerCopyright?: string | null;
  homeHeroHeading?: string | null;
  homeHeroSubtitle?: string | null;
  homeHeroBookingHeading?: string | null;
  homeHeroBookingDescription?: string | null;
  homeManifestoLabel?: string | null;
  homeManifestoDetailsButtonLabel?: string | null;
  homeManifestoSegments?:
    | {
        type: 'text' | 'highlight' | 'divider';
        content?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Usado como fallback quando uma pagina nao tem metaTitle. Max 60 chars.
   */
  defaultMetaTitle?: string | null;
  /**
   * Usado como fallback quando uma pagina nao tem metaDescription. Ideal: 120-155 chars.
   */
  defaultMetaDescription?: string | null;
  /**
   * Imagem padrao para compartilhamento em redes sociais. Tamanho ideal: 1200x630px.
   */
  defaultOgImage?: string | null;
  /**
   * URL base do site em producao. Ex: https://itaicypantanal.com.br. Usada para gerar canonical URLs e sitemap.
   */
  siteUrl?: string | null;
  /**
   * Codigo de verificacao do Google Search Console. Sera injetado como meta tag.
   */
  googleSiteVerification?: string | null;
  /**
   * JSON com chaves por rota (ex: '/', '/acomodacoes'). Cada rota contem os textos, imagens e dados de todas as secoes da pagina.
   */
  pageContent?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * ATENCAO: Este campo sera descontinuado. Edite o conteudo nas abas acima.
   */
  sharedSections?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  contactEmail?: T;
  contactPhone?: T;
  contactAddress?: T;
  ctaHeading?: T;
  ctaDescription?: T;
  ctaBackgroundImage?: T;
  faqLabel?: T;
  faqHeading?: T;
  faqDescription?: T;
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  testimonialsLabel?: T;
  testimonialsHeading?: T;
  testimonialsDescription?: T;
  testimonialItems?:
    | T
    | {
        quote?: T;
        author?: T;
        location?: T;
        rating?: T;
        id?: T;
      };
  footerPousadaLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerExperienciasLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerLegalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerCopyright?: T;
  homeHeroHeading?: T;
  homeHeroSubtitle?: T;
  homeHeroBookingHeading?: T;
  homeHeroBookingDescription?: T;
  homeManifestoLabel?: T;
  homeManifestoDetailsButtonLabel?: T;
  homeManifestoSegments?:
    | T
    | {
        type?: T;
        content?: T;
        id?: T;
      };
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  defaultOgImage?: T;
  siteUrl?: T;
  googleSiteVerification?: T;
  pageContent?: T;
  sharedSections?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}