/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    'blog-posts': BlogPost;
    'blog-categories': BlogCategory;
    'bird-species': BirdSpecy;
    'bird-categories': BirdCategory;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    'bird-species': BirdSpeciesSelect<false> | BirdSpeciesSelect<true>;
    'bird-categories': BirdCategoriesSelect<false> | BirdCategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'agent-config': AgentConfig;
    'site-settings': SiteSetting;
    'home-content': HomeContent;
    'acomodacoes-content': AcomodacoesContent;
    'culinaria-content': CulinariaContent;
    'pesca-content': PescaContent;
    'ecoturismo-content': EcoturismoContent;
    'birdwatching-content': BirdwatchingContent;
    'contato-content': ContatoContent;
    'nosso-impacto-content': NossoImpactoContent;
    'privacidade-content': PrivacidadeContent;
    'not-found-content': NotFoundContent;
  };
  globalsSelect: {
    'agent-config': AgentConfigSelect<false> | AgentConfigSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-content': HomeContentSelect<false> | HomeContentSelect<true>;
    'acomodacoes-content': AcomodacoesContentSelect<false> | AcomodacoesContentSelect<true>;
    'culinaria-content': CulinariaContentSelect<false> | CulinariaContentSelect<true>;
    'pesca-content': PescaContentSelect<false> | PescaContentSelect<true>;
    'ecoturismo-content': EcoturismoContentSelect<false> | EcoturismoContentSelect<true>;
    'birdwatching-content': BirdwatchingContentSelect<false> | BirdwatchingContentSelect<true>;
    'contato-content': ContatoContentSelect<false> | ContatoContentSelect<true>;
    'nosso-impacto-content': NossoImpactoContentSelect<false> | NossoImpactoContentSelect<true>;
    'privacidade-content': PrivacidadeContentSelect<false> | PrivacidadeContentSelect<true>;
    'not-found-content': NotFoundContentSelect<false> | NotFoundContentSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Edite as secoes de cada rota do site mantendo a mesma estrutura JSON.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Nome para identificar a pagina no CMS (nao aparece no site).
   */
  title?: string | null;
  /**
   * Use a rota completa, ex.: /, /blog, /observacao-de-aves.
   */
  slug: string;
  /**
   * Deixe vazio para usar automaticamente: "{title} | Itaicy Pantanal Eco Lodge". Maximo recomendado: 60 caracteres.
   */
  metaTitle?: string | null;
  /**
   * Deixe vazio para usar automaticamente os primeiros 155 caracteres do campo "title". Ideal: 120-155 caracteres.
   */
  metaDescription?: string | null;
  /**
   * Deixe vazio para usar automaticamente o campo "title". Tamanho ideal: 1200x630px.
   */
  ogImage?: string | null;
  /**
   * Marque para impedir que esta pagina apareca nos resultados de busca.
   */
  noIndex?: boolean | null;
  /**
   * Deixe vazio para usar automaticamente: "http://127.0.0.1:5000/{slug}". Preencha apenas se a URL canonica for diferente.
   */
  canonicalUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Central de imagens e arquivos visuais usados no site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descreva a imagem para leitores de tela e para melhorar SEO.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Gerencie os artigos do blog com categorias, destaque e conteudo estruturado.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  /**
   * Titulo principal do artigo. Aparece no card e na pagina.
   */
  title: string;
  /**
   * URL amigavel do artigo (somente minusculas e hifens).
   */
  slug: string;
  subtitle?: string | null;
  description?: string | null;
  tag?: string | null;
  primaryCategory?: (number | null) | BlogCategory;
  categories?: (number | BlogCategory)[] | null;
  src?: string | null;
  /**
   * Caminho da imagem principal usada no hero do artigo.
   */
  heroImage?: string | null;
  author?: string | null;
  date?: string | null;
  readingTime?: string | null;
  contentBlocks?:
    | (
        | {
            /**
             * Use **texto** para negrito (compativel com markdown).
             */
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading';
          }
        | {
            name: string;
            scientificName: string;
            description: string;
            /**
             * Caminho da imagem, ex: /images/bird-species-1
             */
            image?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'species';
          }
        | {
            items?:
              | {
                  bold: string;
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'orderedList';
          }
      )[]
    | null;
  /**
   * Deixe vazio para usar automaticamente: "{title} | Itaicy Pantanal Eco Lodge". Maximo recomendado: 60 caracteres.
   */
  metaTitle?: string | null;
  /**
   * Deixe vazio para usar automaticamente os primeiros 155 caracteres do campo "description". Ideal: 120-155 caracteres.
   */
  metaDescription?: string | null;
  /**
   * Deixe vazio para usar automaticamente o campo "heroImage". Tamanho ideal: 1200x630px.
   */
  ogImage?: string | null;
  /**
   * Marque para impedir que esta pagina apareca nos resultados de busca.
   */
  noIndex?: boolean | null;
  /**
   * Deixe vazio para usar automaticamente: "http://127.0.0.1:5000/blog/{slug}". Preencha apenas se a URL canonica for diferente.
   */
  canonicalUrl?: string | null;
  relatedPosts?: (number | BlogPost)[] | null;
  /**
   * Marque para exibir como artigo principal na pagina do blog.
   */
  isFeatured?: boolean | null;
  /**
   * Marque para exibir na secao 'Mais Recentes' do blog.
   */
  isRecent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Classifique os artigos para melhorar navegacao, filtros e SEO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  /**
   * Ex.: Aventura, Sustentabilidade, Gastronomia.
   */
  name: string;
  /**
   * URL amigavel da categoria. Use letras minusculas e hifens.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Catalogo de especies para paginas de observacao de aves e conteudo editorial.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bird-species".
 */
export interface BirdSpecy {
  id: number;
  commonName: string;
  scientificName: string;
  slug: string;
  description?: string | null;
  /**
   * Ex: Psittaciformes, Passeriformes
   */
  taxonomicOrder?: string | null;
  /**
   * Ex: Psittacidae, Thraupidae
   */
  family?: string | null;
  commonNameEN?: string | null;
  category?: (number | null) | BirdCategory;
  tag?: string | null;
  src?: string | null;
  heroImage?: string | null;
  author?: string | null;
  date?: string | null;
  /**
   * Status IUCN. Ex: 'Vulneravel (VU)', 'Pouco Preocupante (LC)'
   */
  conservationStatus?: string | null;
  size?: string | null;
  /**
   * Marque para exibir na secao de aves em destaque.
   */
  isFeatured?: boolean | null;
  habitat?: string | null;
  overview?: string | null;
  diet?: string | null;
  behavior?: string | null;
  bestTime?: string | null;
  /**
   * Dicas praticas para fotografar esta especie no Pantanal.
   */
  photographyTips?:
    | {
        tip: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Deixe vazio para usar automaticamente: "{commonName} | Itaicy Pantanal Eco Lodge". Maximo recomendado: 60 caracteres.
   */
  metaTitle?: string | null;
  /**
   * Deixe vazio para usar automaticamente os primeiros 155 caracteres do campo "description". Ideal: 120-155 caracteres.
   */
  metaDescription?: string | null;
  /**
   * Deixe vazio para usar automaticamente o campo "heroImage". Tamanho ideal: 1200x630px.
   */
  ogImage?: string | null;
  /**
   * Marque para impedir que esta pagina apareca nos resultados de busca.
   */
  noIndex?: boolean | null;
  /**
   * Deixe vazio para usar automaticamente: "http://127.0.0.1:5000/observacao-de-aves/catalogo/{slug}". Preencha apenas se a URL canonica for diferente.
   */
  canonicalUrl?: string | null;
  relatedSpecies?: (number | BirdSpecy)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Organize as especies por grupos para facilitar busca e filtragem.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bird-categories".
 */
export interface BirdCategory {
  id: number;
  /**
   * Ex.: Rapinantes, Aves aquaticas, Psitacideos.
   */
  name: string;
  /**
   * URL amigavel da categoria. Use letras minusculas e hifens.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gerencie os acessos de quem pode editar o site no CMS.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Nome exibido no painel administrativo.
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'bird-species';
        value: number | BirdSpecy;
      } | null)
    | ({
        relationTo: 'bird-categories';
        value: number | BirdCategory;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  noIndex?: T;
  canonicalUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  description?: T;
  tag?: T;
  primaryCategory?: T;
  categories?: T;
  src?: T;
  heroImage?: T;
  author?: T;
  date?: T;
  readingTime?: T;
  contentBlocks?:
    | T
    | {
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        heading?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        species?:
          | T
          | {
              name?: T;
              scientificName?: T;
              description?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        orderedList?:
          | T
          | {
              items?:
                | T
                | {
                    bold?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  noIndex?: T;
  canonicalUrl?: T;
  relatedPosts?: T;
  isFeatured?: T;
  isRecent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bird-species_select".
 */
export interface BirdSpeciesSelect<T extends boolean = true> {
  commonName?: T;
  scientificName?: T;
  slug?: T;
  description?: T;
  taxonomicOrder?: T;
  family?: T;
  commonNameEN?: T;
  category?: T;
  tag?: T;
  src?: T;
  heroImage?: T;
  author?: T;
  date?: T;
  conservationStatus?: T;
  size?: T;
  isFeatured?: T;
  habitat?: T;
  overview?: T;
  diet?: T;
  behavior?: T;
  bestTime?: T;
  photographyTips?:
    | T
    | {
        tip?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  noIndex?: T;
  canonicalUrl?: T;
  relatedSpecies?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bird-categories_select".
 */
export interface BirdCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configuracoes operacionais editaveis do agente: disclaimers, handoff, fallback e saudacao.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-config".
 */
export interface AgentConfig {
  id: number;
  enabled?: boolean | null;
  assistantName: string;
  bookingEngineUrl: string;
  /**
   * Abaixo deste valor o agente deve evitar resposta definitiva e priorizar handoff humano.
   */
  faqConfidenceThreshold: number;
  priceDisclaimer: {
    pt: string;
    en: string;
    es: string;
  };
  availabilityDisclaimer: {
    pt: string;
    en: string;
    es: string;
  };
  policyDisclaimer: {
    pt: string;
    en: string;
    es: string;
  };
  handoff: {
    email: string;
    emergencyPhone: string;
    whatsapp: string;
    serviceHours: string;
    slaHours: number;
  };
  genericErrorFallback: {
    pt: string;
    en: string;
    es: string;
  };
  apiUnavailableFallback: {
    pt: string;
    en: string;
    es: string;
  };
  leadConsentPrompt: {
    pt: string;
    en: string;
    es: string;
  };
  leadSuccessMessage: {
    pt: string;
    en: string;
    es: string;
  };
  welcomeGreeting: {
    pt: string;
    en: string;
    es: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configuracoes globais compartilhadas em todo o site: contato, rodape, FAQ, depoimentos e secoes da home.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  contactAddress?: string | null;
  ctaHeading?: string | null;
  ctaDescription?: string | null;
  /**
   * Caminho da imagem, ex: /images/cta-bg
   */
  ctaBackgroundImage?: string | null;
  faqLabel?: string | null;
  faqHeading?: string | null;
  faqDescription?: string | null;
  /**
   * Adicione perguntas frequentes. Arraste para reordenar.
   */
  faqItems?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  testimonialsLabel?: string | null;
  testimonialsHeading?: string | null;
  testimonialsDescription?: string | null;
  testimonialItems?:
    | {
        quote: string;
        author: string;
        location?: string | null;
        rating?: number | null;
        id?: string | null;
      }[]
    | null;
  footerPousadaLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerExperienciasLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerLegalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerCopyright?: string | null;
  /**
   * Usado como fallback quando uma pagina nao tem metaTitle. Max 60 chars.
   */
  defaultMetaTitle?: string | null;
  /**
   * Usado como fallback quando uma pagina nao tem metaDescription. Ideal: 120-155 chars.
   */
  defaultMetaDescription?: string | null;
  /**
   * Imagem padrao para compartilhamento em redes sociais. Tamanho ideal: 1200x630px.
   */
  defaultOgImage?: string | null;
  /**
   * URL base do site em producao. Ex: https://itaicypantanal.com.br. Usada para gerar canonical URLs e sitemap.
   */
  siteUrl?: string | null;
  /**
   * Codigo de verificacao do Google Search Console. Sera injetado como meta tag.
   */
  googleSiteVerification?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Conteudo editavel da pagina inicial.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content".
 */
export interface HomeContent {
  id: number;
  aboutUs?: {
    label?: string | null;
    heading?: string | null;
    body?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Ex: /images/pesca-about-1
     */
    image?: string | null;
    features?:
      | {
          number?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  expeditions?: {
    label?: string | null;
    heading?: string | null;
    description?: string | null;
    items?:
      | {
          title: string;
          description?: string | null;
          backgroundImage?: string | null;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
    buttonText?: string | null;
  };
  stats?: {
    items?:
      | {
          target: number;
          suffix?: string | null;
          label?: string | null;
          hasIcon?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  accommodation?: {
    label?: string | null;
    heading?: string | null;
    body?: string | null;
    buttonReserve?: string | null;
    buttonDetails?: string | null;
    backgroundImage?: string | null;
  };
  impact?: {
    label?: string | null;
    heading?: string | null;
    items?:
      | {
          number?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    image?: string | null;
  };
  blog?: {
    label?: string | null;
    heading?: string | null;
    description?: string | null;
    buttonText?: string | null;
  };
  faq: {
    label?: string | null;
    heading: string;
    description?: string | null;
    items?:
      | {
          id: string;
          number: string;
          question: string;
          answer: string;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Conteudo editavel da pagina de acomodacoes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "acomodacoes-content".
 */
export interface AcomodacoesContent {
  id: number;
  hero: {
    label?: string | null;
    heading: string;
    subtitle?: string | null;
    description?: string | null;
    scrollHint?: string | null;
    /**
     * Ex: /images/pesca-hero-bg.webp
     */
    backgroundImage?: string | null;
    videoMp4?: string | null;
    videoWebm?: string | null;
    videoMp4Low?: string | null;
    videoWebmLow?: string | null;
    videoPoster?: string | null;
  };
  manifesto?: {
    /**
     * Cada segmento e um trecho de texto. Marque 'Destaque' para texto dourado.
     */
    segments?:
      | {
          text: string;
          isHighlight?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  highlights?: {
    heading?: string | null;
    items?:
      | {
          /**
           * Ex: Fish, Star, Compass
           */
          iconName?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  rooms?:
    | {
        title: string;
        description?: string | null;
        image?: string | null;
        ctaText?: string | null;
        features?:
          | {
              iconName?: string | null;
              label?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  culinary?: {
    label?: string | null;
    heading?: string | null;
    description?: string | null;
    images?:
      | {
          src: string;
          alt?: string | null;
          tag?: string | null;
          id?: string | null;
        }[]
      | null;
    ctaText?: string | null;
    ctaHref?: string | null;
  };
  faq: {
    label?: string | null;
    heading: string;
    description?: string | null;
    items?:
      | {
          id: string;
          number: string;
          question: string;
          answer: string;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Conteudo editavel da pagina de culinaria.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "culinaria-content".
 */
export interface CulinariaContent {
  id: number;
  hero: {
    label?: string | null;
    heading: string;
    subtitle?: string | null;
    description?: string | null;
    scrollHint?: string | null;
    /**
     * Ex: /images/pesca-hero-bg.webp
     */
    backgroundImage?: string | null;
  };
  manifesto?: {
    /**
     * Cada segmento e um trecho de texto. Marque 'Destaque' para texto dourado.
     */
    segments?:
      | {
          text: string;
          isHighlight?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  menu?: {
    label?: string | null;
    heading?: string | null;
    body?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Ex: /images/pesca-about-1
     */
    image?: string | null;
    features?:
      | {
          number?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  highlights?: {
    heading?: string | null;
    items?:
      | {
          /**
           * Ex: Fish, Star, Compass
           */
          iconName?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  services?: {
    label?: string | null;
    heading?: string | null;
    description?: string | null;
    items?:
      | {
          title: string;
          description?: string | null;
          image?: string | null;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
    buttonText?: string | null;
    buttonHref?: string | null;
  };
  experience?: {
    heading?: string | null;
    body?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    image?: string | null;
  };
  crossSell?: {
    heading?: string | null;
    description?: string | null;
    buttonText?: string | null;
    buttonHref?: string | null;
    image?: string | null;
  };
  faq: {
    label?: string | null;
    heading: string;
    description?: string | null;
    items?:
      | {
          id: string;
          number: string;
          question: string;
          answer: string;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Conteudo editavel da pagina de pesca esportiva.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pesca-content".
 */
export interface PescaContent {
  id: number;
  hero: {
    label?: string | null;
    heading: string;
    subtitle?: string | null;
    description?: string | null;
    scrollHint?: string | null;
    /**
     * Ex: /images/pesca-hero-bg.webp
     */
    backgroundImage?: string | null;
  };
  manifesto?: {
    /**
     * Cada segmento e um trecho de texto. Marque 'Destaque' para texto dourado.
     */
    segments?:
      | {
          text: string;
          isHighlight?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  sobreNos?: {
    label?: string | null;
    heading?: string | null;
    body?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Ex: /images/pesca-about-1
     */
    image?: string | null;
    features?:
      | {
          number?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  highlights?: {
    heading?: string | null;
    items?:
      | {
          /**
           * Ex: Fish, Star, Compass
           */
          iconName?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  services?: {
    label?: string | null;
    heading?: string | null;
    description?: string | null;
    items?:
      | {
          title: string;
          description?: string | null;
          image?: string | null;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
    buttonText?: string | null;
    buttonHref?: string | null;
  };
  faq: {
    label?: string | null;
    heading: string;
    description?: string | null;
    items?:
      | {
          id: string;
          number: string;
          question: string;
          answer: string;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Conteudo editavel da pagina de ecoturismo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ecoturismo-content".
 */
export interface EcoturismoContent {
  id: number;
  hero: {
    label?: string | null;
    heading: string;
    subtitle?: string | null;
    description?: string | null;
    scrollHint?: string | null;
    /**
     * Ex: /images/pesca-hero-bg.webp
     */
    backgroundImage?: string | null;
  };
  manifesto?: {
    /**
     * Cada segmento e um trecho de texto. Marque 'Destaque' para texto dourado.
     */
    segments?:
      | {
          text: string;
          isHighlight?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  sobreNos?: {
    label?: string | null;
    heading?: string | null;
    body?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Ex: /images/pesca-about-1
     */
    image?: string | null;
    features?:
      | {
          number?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  highlights?: {
    heading?: string | null;
    items?:
      | {
          /**
           * Ex: Fish, Star, Compass
           */
          iconName?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  services?: {
    label?: string | null;
    heading?: string | null;
    description?: string | null;
    items?:
      | {
          title: string;
          description?: string | null;
          image?: string | null;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
    buttonText?: string | null;
    buttonHref?: string | null;
  };
  faq: {
    label?: string | null;
    heading: string;
    description?: string | null;
    items?:
      | {
          id: string;
          number: string;
          question: string;
          answer: string;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Conteudo editavel da pagina de observacao de aves.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "birdwatching-content".
 */
export interface BirdwatchingContent {
  id: number;
  hero: {
    label?: string | null;
    heading: string;
    subtitle?: string | null;
    description?: string | null;
    scrollHint?: string | null;
    /**
     * Ex: /images/pesca-hero-bg.webp
     */
    backgroundImage?: string | null;
  };
  manifesto?: {
    /**
     * Cada segmento e um trecho de texto. Marque 'Destaque' para texto dourado.
     */
    segments?:
      | {
          text: string;
          isHighlight?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  sobreNos?: {
    label?: string | null;
    heading?: string | null;
    body?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Ex: /images/pesca-about-1
     */
    image?: string | null;
    features?:
      | {
          number?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  highlights?: {
    heading?: string | null;
    items?:
      | {
          /**
           * Ex: Fish, Star, Compass
           */
          iconName?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  faq: {
    label?: string | null;
    heading: string;
    description?: string | null;
    items?:
      | {
          id: string;
          number: string;
          question: string;
          answer: string;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Conteudo editavel da pagina de contato.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contato-content".
 */
export interface ContatoContent {
  id: number;
  hero: {
    label?: string | null;
    heading: string;
    subtitle?: string | null;
    description?: string | null;
    scrollHint?: string | null;
    /**
     * Ex: /images/pesca-hero-bg.webp
     */
    backgroundImage?: string | null;
  };
  formTitle?: string | null;
  steps?: {
    placeholders?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    buttonNext?: string | null;
    buttonBack?: string | null;
    buttonSubmit?: string | null;
  };
  channels?: {
    heading?: string | null;
    items?:
      | {
          iconName?: string | null;
          title?: string | null;
          info?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  mapCoords?: {
    lat?: number | null;
    lng?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Conteudo editavel da pagina Nosso Impacto (conservacao).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nosso-impacto-content".
 */
export interface NossoImpactoContent {
  id: number;
  hero: {
    label?: string | null;
    heading: string;
    subtitle?: string | null;
    description?: string | null;
    scrollHint?: string | null;
    /**
     * Ex: /images/pesca-hero-bg.webp
     */
    backgroundImage?: string | null;
  };
  manifesto?: {
    /**
     * Cada segmento e um trecho de texto. Marque 'Destaque' para texto dourado.
     */
    segments?:
      | {
          text: string;
          isHighlight?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  rioVivo?: {
    heading?: string | null;
    description?: string | null;
    steps?:
      | {
          iconName?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  biodiversidade?: {
    heading?: string | null;
    description?: string | null;
    counters?:
      | {
          target: number;
          suffix?: string | null;
          label?: string | null;
          hasIcon?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  comunidade?: {
    heading?: string | null;
    description?: string | null;
    body?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    image?: string | null;
  };
  operacao?: {
    heading?: string | null;
    description?: string | null;
    practices?:
      | {
          iconName?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  engagement?: {
    heading?: string | null;
    description?: string | null;
    buttonText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Conteudo editavel da politica de privacidade.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacidade-content".
 */
export interface PrivacidadeContent {
  id: number;
  hero?: {
    title?: string | null;
    lastUpdated?: string | null;
  };
  sections?:
    | {
        id: string;
        title: string;
        /**
         * Cada item e um paragrafo. Comece com ** para criar itens de lista com negrito.
         */
        content?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Conteudo da pagina de erro 404.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "not-found-content".
 */
export interface NotFoundContent {
  id: number;
  hero: {
    label?: string | null;
    heading: string;
    subtitle?: string | null;
    description?: string | null;
    scrollHint?: string | null;
    /**
     * Ex: /images/pesca-hero-bg.webp
     */
    backgroundImage?: string | null;
  };
  buttonText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-config_select".
 */
export interface AgentConfigSelect<T extends boolean = true> {
  enabled?: T;
  assistantName?: T;
  bookingEngineUrl?: T;
  faqConfidenceThreshold?: T;
  priceDisclaimer?:
    | T
    | {
        pt?: T;
        en?: T;
        es?: T;
      };
  availabilityDisclaimer?:
    | T
    | {
        pt?: T;
        en?: T;
        es?: T;
      };
  policyDisclaimer?:
    | T
    | {
        pt?: T;
        en?: T;
        es?: T;
      };
  handoff?:
    | T
    | {
        email?: T;
        emergencyPhone?: T;
        whatsapp?: T;
        serviceHours?: T;
        slaHours?: T;
      };
  genericErrorFallback?:
    | T
    | {
        pt?: T;
        en?: T;
        es?: T;
      };
  apiUnavailableFallback?:
    | T
    | {
        pt?: T;
        en?: T;
        es?: T;
      };
  leadConsentPrompt?:
    | T
    | {
        pt?: T;
        en?: T;
        es?: T;
      };
  leadSuccessMessage?:
    | T
    | {
        pt?: T;
        en?: T;
        es?: T;
      };
  welcomeGreeting?:
    | T
    | {
        pt?: T;
        en?: T;
        es?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  contactEmail?: T;
  contactPhone?: T;
  contactAddress?: T;
  ctaHeading?: T;
  ctaDescription?: T;
  ctaBackgroundImage?: T;
  faqLabel?: T;
  faqHeading?: T;
  faqDescription?: T;
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  testimonialsLabel?: T;
  testimonialsHeading?: T;
  testimonialsDescription?: T;
  testimonialItems?:
    | T
    | {
        quote?: T;
        author?: T;
        location?: T;
        rating?: T;
        id?: T;
      };
  footerPousadaLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerExperienciasLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerLegalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerCopyright?: T;
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  defaultOgImage?: T;
  siteUrl?: T;
  googleSiteVerification?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content_select".
 */
export interface HomeContentSelect<T extends boolean = true> {
  aboutUs?:
    | T
    | {
        label?: T;
        heading?: T;
        body?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
        features?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  expeditions?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              backgroundImage?: T;
              href?: T;
              id?: T;
            };
        buttonText?: T;
      };
  stats?:
    | T
    | {
        items?:
          | T
          | {
              target?: T;
              suffix?: T;
              label?: T;
              hasIcon?: T;
              id?: T;
            };
      };
  accommodation?:
    | T
    | {
        label?: T;
        heading?: T;
        body?: T;
        buttonReserve?: T;
        buttonDetails?: T;
        backgroundImage?: T;
      };
  impact?:
    | T
    | {
        label?: T;
        heading?: T;
        items?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        image?: T;
      };
  blog?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        buttonText?: T;
      };
  faq?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              id?: T;
              number?: T;
              question?: T;
              answer?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "acomodacoes-content_select".
 */
export interface AcomodacoesContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        label?: T;
        heading?: T;
        subtitle?: T;
        description?: T;
        scrollHint?: T;
        backgroundImage?: T;
        videoMp4?: T;
        videoWebm?: T;
        videoMp4Low?: T;
        videoWebmLow?: T;
        videoPoster?: T;
      };
  manifesto?:
    | T
    | {
        segments?:
          | T
          | {
              text?: T;
              isHighlight?: T;
              id?: T;
            };
      };
  highlights?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              iconName?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  rooms?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        ctaText?: T;
        features?:
          | T
          | {
              iconName?: T;
              label?: T;
              id?: T;
            };
        id?: T;
      };
  culinary?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        images?:
          | T
          | {
              src?: T;
              alt?: T;
              tag?: T;
              id?: T;
            };
        ctaText?: T;
        ctaHref?: T;
      };
  faq?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              id?: T;
              number?: T;
              question?: T;
              answer?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "culinaria-content_select".
 */
export interface CulinariaContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        label?: T;
        heading?: T;
        subtitle?: T;
        description?: T;
        scrollHint?: T;
        backgroundImage?: T;
      };
  manifesto?:
    | T
    | {
        segments?:
          | T
          | {
              text?: T;
              isHighlight?: T;
              id?: T;
            };
      };
  menu?:
    | T
    | {
        label?: T;
        heading?: T;
        body?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
        features?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  highlights?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              iconName?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  services?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              href?: T;
              id?: T;
            };
        buttonText?: T;
        buttonHref?: T;
      };
  experience?:
    | T
    | {
        heading?: T;
        body?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
      };
  crossSell?:
    | T
    | {
        heading?: T;
        description?: T;
        buttonText?: T;
        buttonHref?: T;
        image?: T;
      };
  faq?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              id?: T;
              number?: T;
              question?: T;
              answer?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pesca-content_select".
 */
export interface PescaContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        label?: T;
        heading?: T;
        subtitle?: T;
        description?: T;
        scrollHint?: T;
        backgroundImage?: T;
      };
  manifesto?:
    | T
    | {
        segments?:
          | T
          | {
              text?: T;
              isHighlight?: T;
              id?: T;
            };
      };
  sobreNos?:
    | T
    | {
        label?: T;
        heading?: T;
        body?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
        features?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  highlights?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              iconName?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  services?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              href?: T;
              id?: T;
            };
        buttonText?: T;
        buttonHref?: T;
      };
  faq?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              id?: T;
              number?: T;
              question?: T;
              answer?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ecoturismo-content_select".
 */
export interface EcoturismoContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        label?: T;
        heading?: T;
        subtitle?: T;
        description?: T;
        scrollHint?: T;
        backgroundImage?: T;
      };
  manifesto?:
    | T
    | {
        segments?:
          | T
          | {
              text?: T;
              isHighlight?: T;
              id?: T;
            };
      };
  sobreNos?:
    | T
    | {
        label?: T;
        heading?: T;
        body?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
        features?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  highlights?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              iconName?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  services?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              href?: T;
              id?: T;
            };
        buttonText?: T;
        buttonHref?: T;
      };
  faq?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              id?: T;
              number?: T;
              question?: T;
              answer?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "birdwatching-content_select".
 */
export interface BirdwatchingContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        label?: T;
        heading?: T;
        subtitle?: T;
        description?: T;
        scrollHint?: T;
        backgroundImage?: T;
      };
  manifesto?:
    | T
    | {
        segments?:
          | T
          | {
              text?: T;
              isHighlight?: T;
              id?: T;
            };
      };
  sobreNos?:
    | T
    | {
        label?: T;
        heading?: T;
        body?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
        features?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  highlights?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              iconName?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              id?: T;
              number?: T;
              question?: T;
              answer?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contato-content_select".
 */
export interface ContatoContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        label?: T;
        heading?: T;
        subtitle?: T;
        description?: T;
        scrollHint?: T;
        backgroundImage?: T;
      };
  formTitle?: T;
  steps?:
    | T
    | {
        placeholders?:
          | T
          | {
              text?: T;
              id?: T;
            };
        buttonNext?: T;
        buttonBack?: T;
        buttonSubmit?: T;
      };
  channels?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              iconName?: T;
              title?: T;
              info?: T;
              id?: T;
            };
      };
  mapCoords?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nosso-impacto-content_select".
 */
export interface NossoImpactoContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        label?: T;
        heading?: T;
        subtitle?: T;
        description?: T;
        scrollHint?: T;
        backgroundImage?: T;
      };
  manifesto?:
    | T
    | {
        segments?:
          | T
          | {
              text?: T;
              isHighlight?: T;
              id?: T;
            };
      };
  rioVivo?:
    | T
    | {
        heading?: T;
        description?: T;
        steps?:
          | T
          | {
              iconName?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  biodiversidade?:
    | T
    | {
        heading?: T;
        description?: T;
        counters?:
          | T
          | {
              target?: T;
              suffix?: T;
              label?: T;
              hasIcon?: T;
              id?: T;
            };
      };
  comunidade?:
    | T
    | {
        heading?: T;
        description?: T;
        body?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
      };
  operacao?:
    | T
    | {
        heading?: T;
        description?: T;
        practices?:
          | T
          | {
              iconName?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  engagement?:
    | T
    | {
        heading?: T;
        description?: T;
        buttonText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacidade-content_select".
 */
export interface PrivacidadeContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        lastUpdated?: T;
      };
  sections?:
    | T
    | {
        id?: T;
        title?: T;
        content?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "not-found-content_select".
 */
export interface NotFoundContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        label?: T;
        heading?: T;
        subtitle?: T;
        description?: T;
        scrollHint?: T;
        backgroundImage?: T;
      };
  buttonText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}